gTrainerClassNames:: @ 830FCD4
	.string "EVIL TRAINER$", 13
	.string "DARKNESS$", 13
	.string "LIGHTNESS$", 13
	.string "TEAM AQUA$", 13
	.string "TEAM MAGMA$", 13
	.string "COOLTRAINER$", 13
	.string "ADMINISTRATOR$", 13
	.string "TEAM DARK$", 13
	.string "TEAM LIGHT$", 13
	.string "TEAM MAGMA$", 13
	.string "AQUA ADMIN$", 13
	.string "MAGMA ADMIN$", 13
	.string "AQUA LEADER$", 13
	.string "MAGMA LEADER$", 13
	.string "AQUA BOSS$", 13
	.string "MAGMA BOSS$", 13
	.string "ROCKET ADMIN$", 13
	.string "TEAM ROCKET$", 13
	.string "TEAM SHADOW$", 13
	.string "ROCKET ADMIN$", 13
	.string "SHADOW ADMIN$", 13
	.string "BEAUTY$", 13
	.string "MANLY$", 13
	.string "ROCKET LEADER$", 13
	.string "SHADOW LEADER$", 13
	.string "TRAINER$", 13
	.string "CAMPER$", 13
	.string "PICNICKER$", 13
	.string "TEAM DARKNESS$", 13
	.string "TEAM LIGHTNESS$", 13
	.string "GENTLEMAN$", 13
	.string "ELITE SEVENTEEN$", 13
	.string "GYM LEADER$", 13
	.string "SCHOOL KID$", 13
	.string "SR. AND JR.$", 13
	.string "WINSTRATE$", 13
	.string "POKéFAN$", 13
	.string "YOUNGSTER$", 13
	.string "CHAMPION$", 13
	.string "ROCKET BOSS$", 13
	.string "SHADOW BOSS$", 13
	.string "DRAGON TAMER$", 13
	.string "DARK ADMIN$", 13
	.string "LIGHT ADMIN$", 13
	.string "DARK LEADER$", 13
	.string "LIGHT LEADER$", 13
	.string "DARK BOSS$", 13
	.string "LIGHT BOSS$", 13
	.string "NIGHTWINGQUEEN$", 13
	.string "MAGMA ADMIN$", 13
	.string "PKMN TRAINER$", 13
	.string "BUG CATCHER$", 13
	.string "RANGER$", 13
	.string "MAGMA LEADER$", 13
	.string "LASS$", 13
	.string "YOUNG COUPLE$", 13
	.string "OLD COUPLE$", 13
	.string "ICEWINGKING$", 13
	.string "SKYWING$", 13
	.string "SEAWING$", 13
	.string "RAINWING$", 13
	.string "SANDWING$", 13
	.string "NIGHTWING$", 13
	.string "ICEWING$", 13
	.string "PKMN TRAINER$", 13
	.string "PKMN TRAINER$", 13
	.string "PKMN TRAINER$", 13
