gTrainerClassNames:: @ 830FCD4
	.string "EVIL TRAINER$", 20
	.string "DARKNESS$", 20
	.string "LIGHTNESS$", 20
	.string "TEAM AQUA$", 20
	.string "TEAM MAGMA$", 20
	.string "COOLTRAINER$", 20
	.string "ADMINISTRATOR$", 20
	.string "TEAM DARK$", 20
	.string "TEAM LIGHT$", 20
	.string "TEAM MAGMA$", 20
	.string "AQUA ADMIN$", 20
	.string "MAGMA ADMIN$", 20
	.string "AQUA LEADER$", 20
	.string "MAGMA LEADER$", 20
	.string "AQUA BOSS$", 20
	.string "MAGMA BOSS$", 20
	.string "ROCKET ADMIN$", 20
	.string "TEAM ROCKET$", 20
	.string "TEAM SHADOW$", 20
	.string "ROCKET ADMIN$", 20
	.string "SHADOW ADMIN$", 20
	.string "BEAUTY$", 20
	.string "MANLY$", 20
	.string "ROCKET LEADER$", 20
	.string "SHADOW LEADER$", 20
	.string "TRAINER$", 20
	.string "CAMPER$", 20
	.string "PICNICKER$", 20
	.string "TEAM DARKNESS$", 20
	.string "TEAM LIGHTNESS$", 20
	.string "GENTLEMAN$", 20
	.string "ELITE SEVENTEEN$", 20
	.string "GYM LEADER$", 20
	.string "SCHOOL KID$", 20
	.string "SR. AND JR.$", 20
	.string "WINSTRATE$", 20
	.string "POKéFAN$", 20
	.string "YOUNGSTER$", 20
	.string "CHAMPION$", 20
	.string "ROCKET BOSS$", 20
	.string "SHADOW BOSS$", 20
	.string "DRAGON TAMER$", 20
	.string "DARK ADMIN$", 20
	.string "LIGHT ADMIN$", 20
	.string "DARK LEADER$", 20
	.string "LIGHT LEADER$", 20
	.string "DARK BOSS$", 20
	.string "LIGHT BOSS$", 20
	.string "NIGHTWINGQUEEN$", 20
	.string "MAGMA ADMIN$", 20
	.string "PKMN TRAINER$", 20
	.string "BUG CATCHER$", 20
	.string "RANGER$", 20
	.string "MAGMA LEADER$", 20
	.string "LASS$", 20
	.string "YOUNG COUPLE$", 20
	.string "OLD COUPLE$", 20
	.string "ICEWINGKING$", 20
	.string "SKYWING$", 20
	.string "SEAWING$", 20
	.string "RAINWING$", 20
	.string "SANDWING$", 20
	.string "NIGHTWING$", 20
	.string "ICEWING$", 20
	.string "PKMN TRAINER$", 20
	.string "PKMN TRAINER$", 20
	.string "PKMN TRAINER$", 20
