#ifndef GUARD_TRAINER_CLASSES_H
#define GUARD_TRAINER_CLASSES_H

enum
{
    CLASS_TRAINER, // 0
    CLASS_BOYFRIEND, // 1
    CLASS_GIRLFRIEND, // 2
    CLASS_TEAM_AQUA, // 3
    CLASS_PKMN_BREEDER, // 4
    CLASS_COOL_TRAINER, // 5
    CLASS_BIRDKEEPER, // 6
    CLASS_DEVON_SUPPORT, // 7
    CLASS_DEVON_STAFF, // 8
    CLASS_TEAM_MAGMA, // 9
    CLASS_EXPERT, // 0xA
    CLASS_AQUA_ADMIN, // 0xB
    CLASS_DEVON_CHEIF, // 0xC
    CLASS_AQUA_LEADER, // 0xD
    CLASS_DEVON_NRUDGE, // 0xE
    CLASS_DEVON_MRUDGE, // 0xF
    CLASS_DEVON_MEMBER, // 0x10
    CLASS_INTERVIEWER, // 0x11
    CLASS_TUBER_FEMALE, // 0x12
    CLASS_TUBER_MALE, // 0x13
    CLASS_LADY, // 0x14
    CLASS_BEAUTY, // 0x15
    CLASS_RICH_BOY, // 0x16
    CLASS_DEVON_PRUDGE, // 0x17
    CLASS_DEVON_QRUDGE, // 0x18
    CLASS_DEVON_DIRECT, // 0x19
    CLASS_CAMPER, // 0x1A
    CLASS_PICKNICKER, // 0x1B
    CLASS_DEVON_EMPLOYEE, // 0x1C
    CLASS_DEVON_GRUNT, // 0x1D
    CLASS_DEVON_BOSS, // 0x1E
    CLASS_ELITE_FOUR, // 0x1F
    CLASS_LEADER, // 0x20
    CLASS_SCHOOL_KID, // 0x21
    CLASS_DEVON_COMMAND, // 0x22
    CLASS_WINSTRATE, // 0x23
    CLASS_POKE_FAN, // 0x24
    CLASS_YOUNGSTER, // 0x25
    CLASS_CHAMPION, // 0x26
    CLASS_DEVON_LEADER, // 0x27
    CLASS_DEVON_ADMIN, // 0x28
    CLASS_DEVON_EXEC, // 0x29
    CLASS_DEVON_GRUDGE, // 0x2A
    CLASS_DEVON_FRUDGE, // 0x2B
    CLASS_DEVON_DRUDGE, // 0x2C
    CLASS_DEVON_CRUDGE, // 0x2D
    CLASS_TWINS, // 0x2E
    CLASS_DEVON_PRIN, // 0x2F
    CLASS_DEVON_PRES, // 0x30
    CLASS_MAGMA_ADMIN, // 0x31
    CLASS_PKMN_TRAINER_RIVAL, // 0x32
    CLASS_BUG_CATCHER, // 0x33
    CLASS_PKMN_RANGER, // 0x34
    CLASS_MAGMA_LEADER, // 0x35
    CLASS_LASS, // 0x36
    CLASS_POLICEMAN, // 0x37
    CLASS_POLICEWOMAN, // 0x38
    CLASS_POLICEHUMAN, // 0x39
    CLASS_THEIF, // 0x3A
    CLASS_POLICE, // 0x3B
    CLASS_YOUNG_THUG, // 0x3C
    CLASS_YOUNG_POLICE, // 0x3D
    CLASS_POLICE_OFFICER, // 0x3E
    CLASS_POLICE_CHEIF, // 0x3F
    CLASS_PKMN_TRAINER, // 0x40
    CLASS_PKMN_TRAINER2, // 0x41
    CLASS_PKMN_TRAINER3, // 0x42
    CLASS_AQUA_BOSS, // 0x43
    CLASS_MAGMA_BOSS, // 0x44
};

#endif // GUARD_TRAINER_CLASSES_H
